/* eslint-disable */
// Generated file. Do not edit by hand.

import ChevronRight12Svg from '@safely/ux/assets/icons/12/chevron-right-12.svg';
import InformationCircle12Svg from '@safely/ux/assets/icons/12/information-circle-12.svg';
import Sliders12Svg from '@safely/ux/assets/icons/12/sliders-12.svg';
import Dots14Svg from '@safely/ux/assets/icons/14/dots-14.svg';
import ArrowDown16Svg from '@safely/ux/assets/icons/16/arrow-down-16.svg';
import ArrowLeft16Svg from '@safely/ux/assets/icons/16/arrow-left-16.svg';
import ArrowTop16Svg from '@safely/ux/assets/icons/16/arrow-top-16.svg';
import Block16Svg from '@safely/ux/assets/icons/16/block-16.svg';
import Bulb16Svg from '@safely/ux/assets/icons/16/bulb-16.svg';
import Checkmark16Svg from '@safely/ux/assets/icons/16/checkmark-16.svg';
import ChevronDown16Svg from '@safely/ux/assets/icons/16/chevron-down-16.svg';
import ChevronRight16Svg from '@safely/ux/assets/icons/16/chevron-right-16.svg';
import Copy16Svg from '@safely/ux/assets/icons/16/copy-16.svg';
import ExclamationmarkCircle16Svg from '@safely/ux/assets/icons/16/exclamationmark-circle-16.svg';
import Globe16Svg from '@safely/ux/assets/icons/16/globe-16.svg';
import Human16Svg from '@safely/ux/assets/icons/16/human-16.svg';
import More16Svg from '@safely/ux/assets/icons/16/more-16.svg';
import Pencil16Svg from '@safely/ux/assets/icons/16/pencil-16.svg';
import Plus16Svg from '@safely/ux/assets/icons/16/plus-16.svg';
import Reorder16Svg from '@safely/ux/assets/icons/16/reorder-16.svg';
import SignalHigh16Svg from '@safely/ux/assets/icons/16/signal-high-16.svg';
import SignalLow16Svg from '@safely/ux/assets/icons/16/signal-low-16.svg';
import SignalMedium16Svg from '@safely/ux/assets/icons/16/signal-medium-16.svg';
import Sliders16Svg from '@safely/ux/assets/icons/16/sliders-16.svg';
import Switch16Svg from '@safely/ux/assets/icons/16/switch-16.svg';
import Xmark16Svg from '@safely/ux/assets/icons/16/xmark-16.svg';
import XmarkCircle16Svg from '@safely/ux/assets/icons/16/xmark-circle-16.svg';
import SwapVertical20Svg from '@safely/ux/assets/icons/20/swap-vertical-20.svg';
import ArrowDown28Svg from '@safely/ux/assets/icons/28/arrow-down-28.svg';
import ArrowRight28Svg from '@safely/ux/assets/icons/28/arrow-right-28.svg';
import ArrowTop28Svg from '@safely/ux/assets/icons/28/arrow-top-28.svg';
import Backspace28Svg from '@safely/ux/assets/icons/28/backspace-28.svg';
import Bolt28Svg from '@safely/ux/assets/icons/28/bolt-28.svg';
import Checkmark28Svg from '@safely/ux/assets/icons/28/checkmark-28.svg';
import Copy28Svg from '@safely/ux/assets/icons/28/copy-28.svg';
import Flashlight28Svg from '@safely/ux/assets/icons/28/flashlight-28.svg';
import Home28Svg from '@safely/ux/assets/icons/28/home-28.svg';
import InformationCircle28Svg from '@safely/ux/assets/icons/28/information-circle-28.svg';
import Loader28Svg from '@safely/ux/assets/icons/28/loader-28.svg';
import Message28Svg from '@safely/ux/assets/icons/28/message-28.svg';
import More28Svg from '@safely/ux/assets/icons/28/more-28.svg';
import Plus28Svg from '@safely/ux/assets/icons/28/plus-28.svg';
import QrCodeScan28Svg from '@safely/ux/assets/icons/28/qr-code-scan-28.svg';
import QrCodeScanShield28Svg from '@safely/ux/assets/icons/28/qr-code-scan-shield-28.svg';
import Share28Svg from '@safely/ux/assets/icons/28/share-28.svg';
import ShieldCheckmark28Svg from '@safely/ux/assets/icons/28/shield-checkmark-28.svg';
import ShieldExclamationmark28Svg from '@safely/ux/assets/icons/28/shield-exclamationmark-28.svg';
import Flame32Svg from '@safely/ux/assets/icons/32/flame-32.svg';
import FrameCorner48Svg from '@safely/ux/assets/icons/48/frame-corner-48.svg';
import DeviceLinkSvg from '@safely/ux/assets/icons/56/device-link.svg';
import Globe56Svg from '@safely/ux/assets/icons/56/globe-56.svg';
import Loader56Svg from '@safely/ux/assets/icons/56/loader-56.svg';
import Lock56Svg from '@safely/ux/assets/icons/56/lock-56.svg';
import XmarkCircle56Svg from '@safely/ux/assets/icons/56/xmark-circle-56.svg';
import ChevronRight8Svg from '@safely/ux/assets/icons/8/chevron-right-8.svg';
import AddWallet96Svg from '@safely/ux/assets/icons/96/add-wallet-96.svg';
import AddressBook96Svg from '@safely/ux/assets/icons/96/address-book-96.svg';
import BluetoothAccent96Svg from '@safely/ux/assets/icons/96/bluetooth-accent-96.svg';
import BluetoothExclamationmark96Svg from '@safely/ux/assets/icons/96/bluetooth-exclamationmark-96.svg';
import BluetoothRequired96Svg from '@safely/ux/assets/icons/96/bluetooth-required-96.svg';
import CameraLock96Svg from '@safely/ux/assets/icons/96/camera-lock-96.svg';
import Checkmark96Svg from '@safely/ux/assets/icons/96/checkmark-96.svg';
import DeviceExclamationmark96Svg from '@safely/ux/assets/icons/96/device-exclamationmark-96.svg';
import DeviceLinkArrowRight96Svg from '@safely/ux/assets/icons/96/device-link-arrow-right-96.svg';
import DeviceLinkCheckmark96Svg from '@safely/ux/assets/icons/96/device-link-checkmark-96.svg';
import DeviceLinkExclamationmark96Svg from '@safely/ux/assets/icons/96/device-link-exclamationmark-96.svg';
import ExclamationmarkCircle96Svg from '@safely/ux/assets/icons/96/exclamationmark-circle-96.svg';
import FaceidAndroid96Svg from '@safely/ux/assets/icons/96/faceid-android-96.svg';
import FaceidIos96Svg from '@safely/ux/assets/icons/96/faceid-ios-96.svg';
import Fingerprint96Svg from '@safely/ux/assets/icons/96/fingerprint-96.svg';
import LedgerLogo96Svg from '@safely/ux/assets/icons/96/ledger-logo-96.svg';
import ListKey96Svg from '@safely/ux/assets/icons/96/list-key-96.svg';
import Notifications96Svg from '@safely/ux/assets/icons/96/notifications-96.svg';
import Placeholder96Svg from '@safely/ux/assets/icons/96/placeholder-96.svg';
import Safely96Svg from '@safely/ux/assets/icons/96/safely-96.svg';
import WalletPlus96Svg from '@safely/ux/assets/icons/96/wallet-plus-96.svg';

export const ChevronRight12 = { image: ChevronRight12Svg, size: 12 } as const;
export const InformationCircle12 = { image: InformationCircle12Svg, size: 12 } as const;
export const Sliders12 = { image: Sliders12Svg, size: 12 } as const;
export const Dots14 = { image: Dots14Svg, size: 14 } as const;
export const ArrowDown16 = { image: ArrowDown16Svg, size: 16 } as const;
export const ArrowLeft16 = { image: ArrowLeft16Svg, size: 16 } as const;
export const ArrowTop16 = { image: ArrowTop16Svg, size: 16 } as const;
export const Block16 = { image: Block16Svg, size: 16 } as const;
export const Bulb16 = { image: Bulb16Svg, size: 16 } as const;
export const Checkmark16 = { image: Checkmark16Svg, size: 16 } as const;
export const ChevronDown16 = { image: ChevronDown16Svg, size: 16 } as const;
export const ChevronRight16 = { image: ChevronRight16Svg, size: 16 } as const;
export const Copy16 = { image: Copy16Svg, size: 16 } as const;
export const ExclamationmarkCircle16 = { image: ExclamationmarkCircle16Svg, size: 16 } as const;
export const Globe16 = { image: Globe16Svg, size: 16 } as const;
export const Human16 = { image: Human16Svg, size: 16 } as const;
export const More16 = { image: More16Svg, size: 16 } as const;
export const Pencil16 = { image: Pencil16Svg, size: 16 } as const;
export const Plus16 = { image: Plus16Svg, size: 16 } as const;
export const Reorder16 = { image: Reorder16Svg, size: 16 } as const;
export const SignalHigh16 = { image: SignalHigh16Svg, size: 16 } as const;
export const SignalLow16 = { image: SignalLow16Svg, size: 16 } as const;
export const SignalMedium16 = { image: SignalMedium16Svg, size: 16 } as const;
export const Sliders16 = { image: Sliders16Svg, size: 16 } as const;
export const Switch16 = { image: Switch16Svg, size: 16 } as const;
export const Xmark16 = { image: Xmark16Svg, size: 16 } as const;
export const XmarkCircle16 = { image: XmarkCircle16Svg, size: 16 } as const;
export const SwapVertical20 = { image: SwapVertical20Svg, size: 20 } as const;
export const ArrowDown28 = { image: ArrowDown28Svg, size: 28 } as const;
export const ArrowRight28 = { image: ArrowRight28Svg, size: 28 } as const;
export const ArrowTop28 = { image: ArrowTop28Svg, size: 28 } as const;
export const Backspace28 = { image: Backspace28Svg, size: 28 } as const;
export const Bolt28 = { image: Bolt28Svg, size: 28 } as const;
export const Checkmark28 = { image: Checkmark28Svg, size: 28 } as const;
export const Copy28 = { image: Copy28Svg, size: 28 } as const;
export const Flashlight28 = { image: Flashlight28Svg, size: 28 } as const;
export const Home28 = { image: Home28Svg, size: 28 } as const;
export const InformationCircle28 = { image: InformationCircle28Svg, size: 28 } as const;
export const Loader28 = { image: Loader28Svg, size: 28 } as const;
export const Message28 = { image: Message28Svg, size: 28 } as const;
export const More28 = { image: More28Svg, size: 28 } as const;
export const Plus28 = { image: Plus28Svg, size: 28 } as const;
export const QrCodeScan28 = { image: QrCodeScan28Svg, size: 28 } as const;
export const QrCodeScanShield28 = { image: QrCodeScanShield28Svg, size: 28 } as const;
export const Share28 = { image: Share28Svg, size: 28 } as const;
export const ShieldCheckmark28 = { image: ShieldCheckmark28Svg, size: 28 } as const;
export const ShieldExclamationmark28 = { image: ShieldExclamationmark28Svg, size: 28 } as const;
export const Flame32 = { image: Flame32Svg, size: 32 } as const;
export const FrameCorner48 = { image: FrameCorner48Svg, size: 48 } as const;
export const DeviceLink = { image: DeviceLinkSvg, size: 56 } as const;
export const Globe56 = { image: Globe56Svg, size: 56 } as const;
export const Loader56 = { image: Loader56Svg, size: 56 } as const;
export const Lock56 = { image: Lock56Svg, size: 56 } as const;
export const XmarkCircle56 = { image: XmarkCircle56Svg, size: 56 } as const;
export const ChevronRight8 = { image: ChevronRight8Svg, size: 8 } as const;
export const AddWallet96 = { image: AddWallet96Svg, size: 96 } as const;
export const AddressBook96 = { image: AddressBook96Svg, size: 96 } as const;
export const BluetoothAccent96 = { image: BluetoothAccent96Svg, size: 96 } as const;
export const BluetoothExclamationmark96 = { image: BluetoothExclamationmark96Svg, size: 96 } as const;
export const BluetoothRequired96 = { image: BluetoothRequired96Svg, size: 96 } as const;
export const CameraLock96 = { image: CameraLock96Svg, size: 96 } as const;
export const Checkmark96 = { image: Checkmark96Svg, size: 96 } as const;
export const DeviceExclamationmark96 = { image: DeviceExclamationmark96Svg, size: 96 } as const;
export const DeviceLinkArrowRight96 = { image: DeviceLinkArrowRight96Svg, size: 96 } as const;
export const DeviceLinkCheckmark96 = { image: DeviceLinkCheckmark96Svg, size: 96 } as const;
export const DeviceLinkExclamationmark96 = { image: DeviceLinkExclamationmark96Svg, size: 96 } as const;
export const ExclamationmarkCircle96 = { image: ExclamationmarkCircle96Svg, size: 96 } as const;
export const FaceidAndroid96 = { image: FaceidAndroid96Svg, size: 96 } as const;
export const FaceidIos96 = { image: FaceidIos96Svg, size: 96 } as const;
export const Fingerprint96 = { image: Fingerprint96Svg, size: 96 } as const;
export const LedgerLogo96 = { image: LedgerLogo96Svg, size: 96 } as const;
export const ListKey96 = { image: ListKey96Svg, size: 96 } as const;
export const Notifications96 = { image: Notifications96Svg, size: 96 } as const;
export const Placeholder96 = { image: Placeholder96Svg, size: 96 } as const;
export const Safely96 = { image: Safely96Svg, size: 96 } as const;
export const WalletPlus96 = { image: WalletPlus96Svg, size: 96 } as const;
